PREFIX ex: <http://example.com/> 
SELECT * WHERE {
    ?color a ex:Color.
    ?color ex:name ?colorName.
    ?color ex:complementary ?complementary.
    ?fruit a ex:Fruit.
    ?fruit ex:origin ?fruitOrigin.
    FILTER(?colorName = "yellow" && ?fruitOrigin = "spain")
}